#!/usr/bin/env python3
"""
Render the auto-synced data blocks into index.html.

Reads scholar_stats.json, substack_posts.json and orcid_works.json (all
regenerated by the daily GitHub Action) and rewrites the marked regions of
index.html, so the page is correct the moment it loads with no browser-side
fetching. Every field is stripped of markup and HTML-escaped on the way in,
and links are only emitted for http(s) URLs.

Marked regions in index.html (each pair must appear exactly once):

    <!-- data:metrics -->        citation metrics line
    <!-- data:chart -->          citations-per-year figure (alt text + size)
    <!-- data:posts -->          five most recent Substack posts
    <!-- data:pubs -->           publication list (summary + year groups)
    <!-- data:orcid-updated -->  "updated <Month Year>" stamp

Deterministic: unchanged data produces no diff, so the workflow's commit
step stays quiet. Exits non-zero with a ::error:: line if a marker is
missing or duplicated or a data file is unusable, leaving index.html as is.

Usage:
    python scripts/render_snapshot.py
"""

import html
import json
import re
import struct
import sys
from datetime import datetime
from email.utils import parsedate_to_datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / "index.html"
SCHOLAR_PATH = REPO_ROOT / "scholar_stats.json"
SUBSTACK_PATH = REPO_ROOT / "substack_posts.json"
ORCID_PATH = REPO_ROOT / "orcid_works.json"
CHART_LIGHT = "citations_over_time.png"
CHART_DARK = "citations_over_time_dark.png"

MAX_POSTS = 5
# Editorial choice: conference abstracts and posters stay on ORCID, not on
# the page (the intro sentence above the list says so).
OMITTED_TYPES = {"conference-abstract", "conference-poster"}
FALLBACK_SCHOLAR_URL = "https://scholar.google.com/citations?user=ea2W0QgAAAAJ&amp;hl=en"

TAG_RE = re.compile(r"<[^>]+>")


class RenderError(SystemExit):
    def __init__(self, message):
        super().__init__(f"::error::render_snapshot: {message}")


# --- Text helpers -------------------------------------------------------------


def clean(value):
    """Plain text for HTML: strip any markup, decode entities, escape."""
    text = html.unescape(TAG_RE.sub("", "" if value is None else str(value)))
    return html.escape(" ".join(text.split()), quote=True)


def safe_url(value):
    """An href value, or '' when the URL is not plain http(s)."""
    url = ("" if value is None else str(value)).strip()
    if re.match(r"^https?://", url, re.IGNORECASE):
        return html.escape(url, quote=True)
    return ""


def link(url, text):
    href = safe_url(url)
    if not href:
        return text
    return f'<a href="{href}" target="_blank" rel="noopener noreferrer">{text}</a>'


def month_year_iso(value):
    """'2026-07-27' -> 'July 2026' ('' if unparseable)."""
    try:
        return datetime.strptime(str(value)[:10], "%Y-%m-%d").strftime("%B %Y")
    except (TypeError, ValueError):
        return ""


def month_year_rfc(value):
    """RFC 2822 pubDate -> 'May 2026' ('' if unparseable)."""
    try:
        return parsedate_to_datetime(str(value)).strftime("%B %Y")
    except (TypeError, ValueError, IndexError):
        return ""


def png_size(path):
    """(width, height) from a PNG header, or None."""
    try:
        with open(path, "rb") as handle:
            head = handle.read(24)
    except OSError:
        return None
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", head[16:24])


def load_json(path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as err:
        raise RenderError(f"cannot read {path.name}: {err}")


# --- Block renderers ----------------------------------------------------------


def render_metrics(stats):
    metrics = stats.get("metrics") or {}
    values = [metrics.get("citations"), metrics.get("h_index"), metrics.get("i10_index")]
    if any(v is None for v in values):
        raise RenderError("scholar_stats.json is missing citations/h_index/i10_index")
    citations, h_index, i10 = (clean(v) for v in values)
    profile = safe_url(stats.get("profile_url")) or FALLBACK_SCHOLAR_URL
    when = month_year_iso(stats.get("updated"))
    tail = f", {when}" if when else ""
    return (
        f'<p class="metrics">{citations} citations · h-index {h_index} · i10-index {i10} — '
        f'<a href="{profile}" target="_blank" rel="noopener noreferrer">Google Scholar</a>{tail}</p>'
    )


def render_chart(stats):
    per_year = [
        (clean(entry.get("year")), clean(entry.get("citations")))
        for entry in (stats.get("citations_per_year") or [])
        if entry.get("year") is not None and entry.get("citations") is not None
    ]
    alt = "Bar chart of citations per year"
    if per_year:
        alt += " — " + ", ".join(f"{year}: {count}" for year, count in per_year) + "."
    size = png_size(REPO_ROOT / CHART_LIGHT) or png_size(REPO_ROOT / CHART_DARK)
    dims = f' width="{size[0]}" height="{size[1]}"' if size else ""
    return (
        '<figure class="scholar-chart">\n'
        f'    <img src="{CHART_LIGHT}" alt="{alt}" class="chart-light"{dims} loading="lazy" decoding="async">\n'
        f'    <img src="{CHART_DARK}" alt="{alt}" class="chart-dark"{dims} loading="lazy" decoding="async">\n'
        "    <figcaption>citations per year</figcaption>\n"
        "</figure>"
    )


def render_posts(feed):
    posts = [p for p in (feed.get("posts") or []) if p.get("title")][:MAX_POSTS]
    if not posts:
        raise RenderError("substack_posts.json has no posts")
    items = []
    for post in posts:
        when = month_year_rfc(post.get("pubDate"))
        meta = f' <span class="meta">{when}</span>' if when else ""
        description = clean(post.get("description"))
        body = f'\n    <p class="fine">{description}</p>' if description else ""
        items.append(f"<li>{link(post.get('link'), clean(post.get('title')))}{meta}{body}</li>")
    return "\n".join(items)


def venue_for(work):
    journal = clean(work.get("journal"))
    if journal:
        return journal
    work_type = str(work.get("type") or "").strip().lower()
    if not work_type or work_type == "journal-article":
        return ""
    if work_type == "preprint":
        return "Preprint"
    return clean(work_type.replace("-", " ").capitalize())


def render_pubs(orcid):
    works = [
        w for w in (orcid.get("works") or [])
        if w.get("title") and str(w.get("type") or "").strip().lower() not in OMITTED_TYPES
    ]
    if not works:
        raise RenderError("orcid_works.json has no publishable works")

    by_year = {}
    for work in works:
        try:
            year = int(str(work.get("year") or "").strip() or 0)
        except ValueError:
            year = 0
        by_year.setdefault(year, []).append(work)

    groups = [f'<summary id="pubs-summary">show all {len(works)} publications</summary>']
    for year in sorted(by_year, reverse=True):  # 0 (undated) naturally sorts last
        label = str(year) if year else "undated"
        lines = [f'<div class="pub-year">', f'<div class="year-label">{label}</div>', '<ul class="pubs">']
        for work in by_year[year]:
            entry = link(work.get("url"), clean(work.get("title")))
            venue = venue_for(work)
            if venue:
                entry += f' — <span class="journal">{venue}</span>'
            lines.append(f"    <li>{entry}</li>")
        lines += ["</ul>", "</div>"]
        groups.append("\n".join(lines))
    return "\n".join(groups)


# --- Splicing -----------------------------------------------------------------


def splice(doc, name, content, inline=False):
    start, end = f"<!-- data:{name} -->", f"<!-- /data:{name} -->"
    if doc.count(start) != 1 or doc.count(end) != 1:
        raise RenderError(f"marker data:{name} is missing or duplicated in index.html")
    i = doc.index(start) + len(start)
    j = doc.index(end)
    if j < i:
        raise RenderError(f"marker data:{name} is out of order in index.html")
    if inline:
        return doc[:i] + content + doc[j:]
    # Indent generated lines to match the start marker's line
    line_start = doc.rfind("\n", 0, i) + 1
    indent = re.match(r"[ \t]*", doc[line_start:i]).group(0)
    body = "\n".join(indent + line if line else "" for line in content.split("\n"))
    return doc[:i] + "\n" + body + "\n" + indent + doc[j:]


def main():
    original = INDEX_PATH.read_text(encoding="utf-8")
    scholar = load_json(SCHOLAR_PATH)
    substack = load_json(SUBSTACK_PATH)
    orcid = load_json(ORCID_PATH)

    orcid_updated = month_year_iso(orcid.get("updated"))
    if not orcid_updated:
        raise RenderError("orcid_works.json has no usable 'updated' date")

    doc = original
    doc = splice(doc, "metrics", render_metrics(scholar))
    doc = splice(doc, "chart", render_chart(scholar))
    doc = splice(doc, "posts", render_posts(substack))
    doc = splice(doc, "pubs", render_pubs(orcid))
    doc = splice(doc, "orcid-updated", orcid_updated, inline=True)

    if doc == original:
        print("index.html data blocks unchanged.")
        return
    INDEX_PATH.write_text(doc, encoding="utf-8")
    print("Rendered data blocks into index.html.")


if __name__ == "__main__":
    try:
        main()
    except RenderError as err:
        print(err, file=sys.stderr)
        sys.exit(1)
